### - reduced spacing between features and FAQ on landing page
devsoc-unsw/freerooms pull request #470
Opened 2024-03-28 07:47 UTC by kellysu1

CHANGES: 
fixed the spacing for mobile and tablet sized view for the landing page, in between features and FAQs. 
Added tests for features to make sure everything is still visible. 

HOW TO VIEW: 
Go to landing page and scroll until the end of features and start of FAQs 

Attached is a screenshot of the new spacing. 

<img width="403" alt="Screen Shot 2024-03-28 at 6 43 52 pm" src="https://github.com/devsoc-unsw/freerooms/assets/161106005/720912f4-a776-48d2-bf84-7672e567224c">

2024-03-31 10:21 UTC, richard-xue-vrx approved these changes
Looks perfect to me; spacing is fixed on tablet and mobile view w/ local inspection. Nice job on the tests too!

2024-04-04 11:42 UTC, JessicaF requested changes

2024-04-04 11:42 UTC, JessicaF commented on frontend/__tests__/Features.test.tsx
> +    const BrowseBuildings = screen.getByText("Browse Buildings");
Small nit but can we use camelCase for variables in tests (same for the below tests)

2024-04-04 11:44 UTC, JessicaF commented
I'm having issues on my local site where the Our Features heading is covered by the Browse Buildings block when on mobile/tablet sized screens.

<img width="382" alt="Screenshot 2024-04-04 at 10 41 21 PM" src="https://github.com/devsoc-unsw/freerooms/assets/54833118/5459729b-5631-46df-8678-50bd69de0044">

Also, the boxes end up touching on some screen sizes - could you make it so that there's always a gap on all screen sizes?
<img width="1003" alt="Screenshot 2024-04-04 at 10 43 46 PM" src="https://github.com/devsoc-unsw/freerooms/assets/54833118/83036071-5986-4080-89ad-ee78dd1ef43b">

2024-04-17 06:47 UTC, kellysu1 commented
Hi have addressed all the requests 
- Our features is not covered anymore when in mobile and tablet view 
<img width="409" alt="Screen Shot 2024-04-17 at 4 46 18 pm" src="https://github.com/devsoc-unsw/freerooms/assets/161106005/2a8c8111-52ff-4a55-b380-b2a1bf036b28">

- There is now spaces between each box for the features 
<img width="1142" alt="Screen Shot 2024-04-17 at 4 46 07 pm" src="https://github.com/devsoc-unsw/freerooms/assets/161106005/dbae8350-cd8b-490c-860e-c693a1342baf">

- the naming is also fixed in the testing

2024-04-17 09:17 UTC, JessicaF commented
Thanks for the fix!!

2024-04-27 01:31 UTC, merged