460 bug make faqs wider on mobile view
devsoc-unsw/freerooms pull request #475
Opened 2024-04-04 15:49 UTC by cherisechan

2024-04-17 11:48 UTC, JessicaF commented
@cherisechan Please remember to write a description (check Confluence page - Local Development 101) and incude any relevant screenshots!

2024-04-17 11:54 UTC, JessicaF commented
Good work overall! Thank you for adding the tests as well 🙏

2024-04-17 11:54 UTC, JessicaF requested changes

2024-04-17 11:54 UTC, JessicaF commented on frontend/__tests__/Faq.test.tsx
> +import Faq from "../components/Faq";
Could you please check that these imports are sorted (my VSCode is telling me it isn't currently)

2024-04-19 07:20 UTC, richard-xue-vrx commented on frontend/__tests__/Faq.test.tsx
> +import Faq from "../components/Faq";
This seems to be fine on my end, my VSC doesn't throw anything wrong here.

2024-04-19 07:21 UTC, richard-xue-vrx approved these changes
This looks all good to me; I'm happy with this!

2024-04-19 07:23 UTC, richard-xue-vrx commented on frontend/__tests__/Faq.test.tsx
> +import Faq from "../components/Faq";
Actually that might be because I don't have a default linter on my VSC 💀

2024-04-27 01:29 UTC, JessicaF approved these changes

2024-04-27 01:32 UTC, merged