425 bug available soon text aligned weird sometimes
devsoc-unsw/freerooms pull request #476
Opened 2024-04-06 07:54 UTC by sobariu

Before, the "Available Soon" text was formatted weirdly because the text was overflowing, and so that's why it takes up two lines rather than just one.
This can be reproduced if you go to webster building and set time to 6/3/2024 3:25PM.

This was the image of how it looked before:

![available-soon-before](https://github.com/devsoc-unsw/freerooms/assets/143395013/2eb0ddf1-3d4b-4b55-b02f-be71d1253a64)

I added a line of code that basically sets the text of the status of the rooms to be "nowrap", so it doesn't get the weird formatting. This is how it looks now:

![available-soon-after](https://github.com/devsoc-unsw/freerooms/assets/143395013/25ec826b-ec34-49de-930f-5455f4fa2592)

In terms of testing, I struggled a bit here to test with BuildingDrawer component because I had to render with redux, but then it couldn't fetch the data of the rooms. Therefore, I had to make a new file in 'views
 called `RoomAvailabilityBox.tsx`, which allowed me to export the component and test it directly. 
 
 Note though that I didn't really delete any code from `BuildingDrawer.tsx`, so there's duplicate code in `RoomAvailabilityBox.tsx` and `BuildingDrawer.tsx`.

2024-04-17 12:02 UTC, JessicaF requested changes

2024-04-17 12:02 UTC, JessicaF commented on frontend/views/RoomAvailabilityBox.tsx
> +import { RoomStatus } from "@common/types";
When you make this new `RoomAvailabilityBox` component, you can remove the one declared in `BuildingDrawer` and just import this one instead. Usually you wouldn't make a new component and just use it in your test (but rather you'd call it in other components too)

2024-04-17 12:02 UTC, JessicaF commented on frontend/__tests__/RoomAvailabilityBox.test.tsx
> +import RoomAvailabilityBox from "../views/RoomAvailabilityBox";
Could you please check that your imports are sorted correctly - on my local VSCode there is a linting error

2024-04-21 10:19 UTC, sobariu commented on frontend/__tests__/RoomAvailabilityBox.test.tsx
> +import RoomAvailabilityBox from "../views/RoomAvailabilityBox";
I am unsure how to check the linting error, because on my VSCode there is no error. I ran npm run lint as well to double check.

2024-04-21 10:20 UTC, sobariu commented on package-lock.json
> +{
I double checked and I don't think I added or removed anything from this file, I don't know why it indicates that there were changes made.

2024-04-21 10:26 UTC, sobariu commented
Hi, I made pushed new changes to the branch. 
- I removed the `RoomAvailabilityBox` component that was declared in `BuildingDrawer.tsx`.
- Test still pass
- In terms of linting, my VSCode says there's no error, although that might be because of how my VSCode is set. I ran npm run lint to double check. 
- In terms of the `package-lock.json` file, I don't recall making any changes to the file, so I am unsure why it says i did. I double checked the file with the one in the main branch and nothing has changed.

2024-04-21 13:01 UTC, SkellyBG commented
> * In terms of the `package-lock.json` file, I don't recall making any changes to the file, so I am unsure why it says i did. I double checked the file with the one in the main branch and nothing has changed.

Looks like you're adding a `package-lock.json` file to the monorepo root (the `package-lock.json` file in the frontend isn't touched!) - you may have accidentally run `npm install` in the root folder instead? In any case, you should remove it from the diff.

> * In terms of linting, my VSCode says there's no error, although that might be because of how my VSCode is set. I ran npm run lint to double check.

Lints seem fine on my VSCode too - @JessicaF could you send the error that your VSCode is having?

2024-04-21 15:00 UTC, sobariu commented
> > * In terms of the `package-lock.json` file, I don't recall making any changes to the file, so I am unsure why it says i did. I double checked the file with the one in the main branch and nothing has changed.
> 
> Looks like you're adding a `package-lock.json` file to the monorepo root (the `package-lock.json` file in the frontend isn't touched!) - you may have accidentally run `npm install` in the root folder instead? In any case, you should remove it from the diff.

Oh thank you for that! I probably did run npm install in the root folder by accident ;-; I made a new push that removes this file :)))

2024-04-27 01:22 UTC, JessicaF approved these changes
Looks good - thanks for the fixes! 🥳

2024-04-27 01:32 UTC, merged