496 Added star ratings to Building Card, Building Drawer and the rooms
devsoc-unsw/freerooms pull request #519
Opened 2024-07-18 03:36 UTC by liviawangg

Changes made:
- Added overall star to buildings 
- Added stars to building drawer
- Added stars to each room

How to view:
- Go to freerooms browse
- Click into a building
- Click into a room

Changes:
<img width="1436" alt="Screenshot 2024-07-18 at 1 33 14 PM" src="https://github.com/user-attachments/assets/aee0a799-8a3b-4bc3-9dfe-0d1dee742edf">
<img width="1440" alt="Screenshot 2024-07-18 at 1 34 35 PM" src="https://github.com/user-attachments/assets/0c215467-535f-4f1f-b353-76f0099de831">

2024-07-18 03:43 UTC, liviawangg commented
Wait I forgot to write tests LOL (i'll do that in a bit) mb

2024-08-19 08:56 UTC, JessicaF requested changes
Overall good! Just left a few comments to help with cleaning up the code 😄 

Let me know how you go with adding the tests as well! For now since there's no interactivity yet, just include tests on if the components are visible where they should be

2024-08-19 08:56 UTC, JessicaF commented on frontend/app/room/[room]/page.tsx
> +          <div style={{ width: 3 }} />
What's the purpose of this `div`? If you're using it to add a gap between the `Typography` and `Rating`, then you should be able to use something like:

```
<Stack direction="row" alignItems="center" gap={3}> 
```

2024-08-19 08:56 UTC, JessicaF commented on frontend/components/BuildingCard.tsx
> +import Rating from "@mui/material/Rating";
Is `Rating` being used as a component in this file?

2024-08-19 08:56 UTC, JessicaF commented on frontend/components/BuildingCard.tsx
> +  const ratingValue = 3;
Where would this variable be used? Is `ratingValue` meant to be in the `Typography` component below instead of the `{4.5}`?

2024-08-19 08:56 UTC, JessicaF commented on frontend/views/RoomAvailabilityBox.tsx
> +            <div style={{ width: 3 }} />
Same comment as `page.tsx`

2024-08-19 08:56 UTC, JessicaF commented on frontend/views/RoomAvailabilityBox.tsx
> +              {" "}
Do we need `{" "}`?

2024-09-18 03:27 UTC, JessicaF commented
@liviawangg Is this PR ready for another review?

2024-09-18 04:32 UTC, liviawangg commented
> @liviawangg Is this PR ready for another review?

yess :>>

2024-09-23 07:01 UTC, JessicaF approved these changes

2024-09-23 07:10 UTC, merged