498 circular display rating
devsoc-unsw/freerooms pull request #525
Opened 2024-07-31 07:58 UTC by sobariu

Inside `BookingCalendar.tsx`, I added a new component called `CircularRating` which creates the circular display of the overall rating of each category for that particular room. I added mock values for the ratings for now until backend is handled. 

![image](https://github.com/user-attachments/assets/3b1b3a87-25df-40a7-a59e-bfba4651abee)

2024-08-19 09:08 UTC, JessicaF requested changes

2024-08-19 09:08 UTC, JessicaF commented on frontend/__tests__/CircularRating.test.tsx
> +import "@testing-library/jest-dom";
Thanks for including tests already!

2024-09-03 05:03 UTC, sobariu commented
![image](https://github.com/user-attachments/assets/d5d94128-e76f-400c-b923-38ea3ed3ca5d)


I've updated `CircularRating` so that the border is reflective of the the rating, as well as changed the color of the border to match in theme with the rest of the application. I've also increased the size of the text.

2024-09-04 03:30 UTC, JessicaF requested changes
Looking much better overall! Left some more comments for you but lmk if you need any more clarifications!

2024-09-04 03:30 UTC, JessicaF commented on frontend/components/BookingCalendar.tsx
> +  const CircularRating: React.FC<{ category: string; rating: number }> = ({
- Can this be moved into its own `CircularRating` component? 
- Does this need to be part of the `BookingCalendar` component? I don't think `CircularRating` should be included here as there shouldn't be a specific connection between the calendar and the ratings. Instead `CircularRating` should be called from inside the `page.tsx` file in the room/[room] folder and then positioned correctly below the `BookingCalendar`

2024-09-04 03:30 UTC, JessicaF commented on frontend/components/BookingCalendar.tsx
> +    return (
Can we have the row of `Circular Ratings` directly aligned to the left-side under the `BookingCalendar` for now? Right now it seems to be positioned a bit off-centre

2024-09-04 03:30 UTC, JessicaF commented on frontend/components/BookingCalendar.tsx
> +        <Typography variant="h6" fontWeight="bold">
Small nit but I feel like having the category names bolded might be too strong? Maybe see what it looks like as just regular, unbolded text?

2024-09-04 03:30 UTC, JessicaF commented on frontend/components/BookingCalendar.tsx
> +        <Box display="flex" flexDirection="row-reverse" mt={2} gap={9} pr={14}>
I think this `Box` should be a new component such as `RoomRatingList` (or some other appropriate name) and then called in the `page.tsx` file I mentioned in my first comment (i.e. don't put the ratings in the same component as `BookingCalendar` because technically they aren't really related functionality-wise)

2024-09-07 09:12 UTC, sobariu commented
I created a new folder `Rooms`, which contains 2 new component files `CircularRating.tsx` and `RoomRating.tsx`. I moved the `CircularRating` component into `CircularRating.tsx` and called it inside `RoomRating.tsx` that has the box component from before. I also made the category font unbolded and aligned the row to the left :))

2024-09-07 09:16 UTC, sobariu commented on frontend/components/BookingCalendar.tsx
> +        <Typography variant="h6" fontWeight="bold">
yep unbolded looks better ahaha

2024-09-20 07:55 UTC, merged