497 feature make the overall rating display
devsoc-unsw/freerooms pull request #533
Opened 2024-09-04 16:20 UTC by azjy89

finished creating the overall rating with dummy data

2024-09-09 11:02 UTC, azjy89 commented
![image](https://github.com/user-attachments/assets/cb914264-29d7-43ff-8f2b-53beba990bc5)
added the overall rating within the individual room pages

![image](https://github.com/user-attachments/assets/a0230544-1a8e-4fa3-8f4a-7684515cc2a9)

as well as adding the modal for submitting a review of a room

2024-09-09 11:16 UTC, azjy89 commented
![image](https://github.com/user-attachments/assets/4b005984-f5b7-4eff-9bd8-6e3370b01215)

resolved mobile ui issue with modal

2024-09-12 03:20 UTC, JessicaF requested changes
Good work overall! Just a couple comments mostly regarding splitting components out of the `OverallRating` component to stop it from getting too chunky and nested.

2024-09-12 03:20 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +            Leave a Review
Can this text be increased? It's a bit hard to read/spot on the page - maybe make it the same size as the other text on the page (such as the school name)? 

<img width="1330" alt="Screenshot 2024-09-12 at 1 07 36 PM" src="https://github.com/user-attachments/assets/853f0d98-c1c0-4436-8597-817d25180215">

2024-09-12 03:20 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +          id="overall-rating"
What is this`id` for?

2024-09-12 03:20 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +          component="h2"
Also was there a specific reason for adding the `component`attribute?

2024-09-12 03:20 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +      <Stack width="300px" height="50%">
I would probably extract this as a separate component if you're putting the "Overall Rating" and `LinearRating` as one `Stack`

2024-09-12 03:20 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +          <Modal
Would make this `Modal` a separate component to avoid deep nesting one file

2024-09-12 03:20 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +                  Submit
Would also increase font size of this text

2024-09-12 03:20 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +                height: "50vh",
Don't think we need this - can keep the height the size of the child elements for now. Big window sizes make there be a large white space at the bottom. 

Might also need to check on mobile sizes if an overflow for scrolling should be specified.

2024-09-12 03:20 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +        <Stack
I would make the 4.5 number and star ratings under it, a single component and call it here

2024-09-12 14:29 UTC, azjy89 commented on frontend/components/OverallRating.tsx
> +        <Stack
made a new component called DecimalStarRating and placed both inside

2024-09-12 14:29 UTC, azjy89 commented on frontend/components/OverallRating.tsx
> +                height: "50vh",
Removed the vh based height

2024-09-12 14:30 UTC, azjy89 commented on frontend/components/OverallRating.tsx
> +          <Modal
Created a new component called ReviewModal to fix this

2024-09-18 03:45 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +            Leave a Review
@azjy89 Did you end up increasing the font size?

2024-09-18 03:57 UTC, JessicaF requested changes
Looking good! Thanks for all the fixes - just left a minor comment about the "Leave a review" and "Submit" buttons.

One thing I've noticed is that opening/closing the modal causes a "bouncing" on the screen - would you be able to fix this?

https://github.com/user-attachments/assets/3f21a734-4b46-41ff-9d64-d58ecade4604

2024-09-18 03:57 UTC, JessicaF commented on frontend/components/OverallRating.tsx
> +            Leave a Review
Also I think leaving the on-hover shadow would give better indications to users that the button is targetable and can be pressed (would do the same for the Submit button as well)

2024-10-02 06:24 UTC, JessicaF approved these changes
Looks good! Thanks for the fixes

2024-10-02 06:28 UTC, merged